services:
  - type: web
    name: book-generator
    env: python
    buildCommand: "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
    startCommand: ".venv/bin/gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
